version: '3.6'
services:
  graphql-engine:
    container_name: speedb_hasura
    build:
      context: .
      dockerfile: ./Dockerfile
    platform: linux/amd64
    environment:
      HASURA_GRAPHQL_DATABASE_URL: ${DATABASE_URL}
#      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
#      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: ${HASURA_GRAPHQL_UNAUTHORIZED_ROLE}
#      HASURA_GRAPHQL_JWT_SECRET: ${HASURA_GRAPHQL_JWT_SECRET}
    restart: always
    ports:
      - "8080:8080"
