version: '3.6'
services:
  graphql-engine:
    container_name: speedb_hasura
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASS}
        - DB_HOST=${DB_HOST}
        - DB_DATABASE=${DB_NAME}
    restart: always
    ports:
      - "8080:8080"
volumes:
  db_data: