-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."segments" add column "best_time" text
--  null default '00:00:00.000000';
